name: Release
on:
  push:
    branches: [main, beta, alpha]
  pull_request:
    branches: [main, beta, alpha]
jobs:
  release:
    name: Release
    environment: staging
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Run package
        run: yarn build
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
